-- Fix UTF-8 mojibake introduced when migration 0030 was applied
--
-- The apply step decoded the migration's base64 GitHub content with
-- browser atob(), which returns a raw byte string rather than proper
-- UTF-8 text — every non-ASCII character (en dashes, curly quotes, the
-- Rupee sign, and all 8 native-script temple names) was corrupted into
-- mojibake in the live database. The INSERT rows themselves and all
-- pure-ASCII columns were unaffected; this repairs the columns that had
-- non-ASCII content, restoring the exact text originally written in
-- migration 0030.

update public.temples set native_name = 'திருப்பரங்குன்றம் முருகன் கோயில்', best_season_notes = 'Jan–Feb for Thaipusam; otherwise Oct–Feb.', sthala_purana = 'Considered the first of the six Arupadaiveedu (sacred battle-camps of Murugan), carved into a rock-cut hillside dating back to around the 6th century under the early Pandyas, with Nayak-era gopurams added later. Tradition holds this is where Murugan married Deivanai, Indra''s daughter, after freeing Indra and the other devas from the demon Surapadman.' where name = 'Thiruparankundram Murugan Temple';
update public.temples set native_name = 'திருச்செந்தூர் முருகன் கோயில்', best_season_notes = 'Oct–Nov for Skanda Sashti, commemorating the victory over Surapadman; otherwise Oct–Feb.', sthala_purana = 'The only one of the six Arupadaiveedu set directly on the seashore, with a documented history reaching back to Sangam-era Tamil literature over 2,000 years old. Tradition holds Murugan established his war camp here before his decisive battle with the demon Surapadman, who could not be slain by any human, animal, or being born of a goddess — Shiva''s third eye had earlier created six divine infants from sparks that merged into Murugan for this very purpose.' where name = 'Tiruchendur Murugan Temple';
update public.temples set native_name = 'சுவாமிமலை முருகன் கோயில்', best_season_notes = 'Oct–Feb.', sthala_purana = 'Set atop a 60-foot hill reached by sixty steps, each named for one of the sixty years of the Tamil calendar. Tradition holds this is where young Murugan explained the meaning of the sacred syllable Om to his own father Shiva, after Shiva could not answer it himself — earning the name Swamimalai, "the hill where Shiva became the student." The temple''s core dates to the Sangam period, with major rebuilding credited to the Chola king Parantaka I.' where name = 'Swamimalai Murugan Temple';
update public.temples set native_name = 'பழமுதிர்சோலை முருகன் கோயில்', best_season_notes = 'Oct–Feb.', sthala_purana = 'The sixth and last of the Arupadaiveedu, set in a forested hill near Madurai, and the only one where Murugan is depicted alongside both his consorts, Valli and Deivanai. Tradition holds this is where the Tamil poet-devotee Avvaiyar, tested by Murugan disguised as a young boy under a tree still worshipped today, was taught a lesson in humility despite her renowned wisdom.' where name = 'Pazhamudircholai Murugan Temple';
update public.temples set native_name = 'కోదండరామ ఆలయం, వొంటిమిట్ట', best_season_notes = 'Mar–Apr for Sri Rama Navami, when the state-sponsored Sita Rama Kalyanam is held here.', sthala_purana = 'A 16th-century Vijayanagara-era temple regarded as one of the finest surviving examples of that architectural style in the Rayalaseema region, and today the official venue for Andhra Pradesh''s state-sponsored Rama Navami wedding celebrations. Tradition holds Rama, Sita, and Lakshmana rested here during their forest exile, and that Rama shot an arrow into the earth to draw water for a thirsty Sita, forming the temple''s two tanks, Ramatirtham and Lakshmanatirtham. The temple''s own name is said to come from two devotees, Vontudu and Mittudu, credited with its construction.' where name = 'Kodandarama Temple, Vontimitta';
update public.temples set native_name = 'ವೈದ್ಯೇಶ್ವರ ದೇವಸ್ಥಾನ, ತಲಕಾಡು', best_season_notes = 'Feb–Mar (Panchalinga Darshana, held once every 12 years, is the biggest event); otherwise Oct–Feb.', sthala_purana = 'Once the capital of the Western Ganga dynasty, and by tradition home to more than thirty temples now mostly buried under Kaveri riverside sand dunes. Local tradition attributes the burial to a curse laid by Queen Alamelamma of Srirangapatna in the 16th century, after Mysore''s Wodeyar rulers seized her jewels — she is said to have drowned herself in the Kaveri, cursing the town to turn to sand; historians instead point to river-course shifts and wind-driven erosion. The Vaidyeshwara Temple is among the few structures still visible above the sand.' where name = 'Vaidyeshwara Temple, Talakadu';
update public.temples set native_name = 'പറശ്ശിനിക്കടവ് മുത്തപ്പൻ ക്ഷേത്രം', best_season_notes = 'Dec–Jan for the Puthari Thiruvappana festival; otherwise Oct–Feb.', sthala_purana = 'A markedly non-traditional temple: worship here centres on the daily Theyyam ritual rather than fixed-idol puja, is open to devotees of every caste and religion, and offers fish, toddy, and meat as prasadam. Local tradition holds Muthappan was a divine child found by a childless couple on the riverbank, whose unconventional habits led to his being cast out, after which he was revealed to combine the forms of Vishnu (as Thiruvappana) and Shiva (as Vellattom). Dogs are considered sacred here as Muthappan’s companions and roam the temple freely.' where name = 'Parassinikadavu Muthappan Temple';
update public.temples set native_name = 'गलताजी मंदिर', best_season_notes = 'Oct–Feb, avoiding peak Rajasthan summer heat.', sthala_purana = 'Known widely as the "Monkey Temple" for the hundreds of macaques living in its Aravalli-hill ravine, alongside seven natural spring-fed water tanks used for ritual bathing. Tradition holds the sage Galav performed 60,000 years of penance here, and that his devotion caused the tanks to be perpetually replenished even in drought. The present temple complex was built under the patronage of Diwan Rao Kripa Ram in the reign of Sawai Jai Singh II.' where name = 'Galtaji Temple';
update public.temples set native_name = 'कालिका माता मंदिर, चित्तौड़गढ़', best_season_notes = 'Sep–Oct for Navaratri; otherwise Oct–Feb.', sthala_purana = 'Originally an 8th-century Surya (sun) temple built by Bappa Rawal, damaged in Alauddin Khalji’s 1303 sack of Chittorgarh Fort, and rededicated to the goddess Kalika (also known locally as Chittodeshwari) after Rana Hamir installed her idol here in the 14th century. The Mewar ruler Maharana Lakshman Singh is credited with lighting an eternal flame (Akhanda Jyoti) here that tradition holds has burned ever since.' where name = 'Kalika Mata Temple, Chittorgarh Fort';
update public.temples set native_name = 'ज्योतिबा मंदिर', best_season_notes = 'Mar–Apr for the Chaitra Yatra fair on Chaitra Purnima.', sthala_purana = 'Set on a hilltop in the Panhala range, with the current structure dating to 1730 under the Maratha noble Ranoji Shinde, replacing an earlier 17th-century shrine. Tradition holds the three gods Brahma, Vishnu, and Shiva combined into a single form, Jyotiba, specifically to destroy the demon Ratnasura and later the demon Raktabhoja, freeing the region from their oppression. The temple''s Chaitra Yatra is known for its colourful processions and clouds of gulal (pink powder).' where name = 'Jyotiba Temple, Kolhapur';
update public.temples set native_name = 'കൊട്ടാരക്കര ഗണപതി ക്ഷേത്രം', best_season_notes = 'Aug–Sep for Vinayaka Chaturthi; otherwise Oct–Feb.', sthala_purana = 'Originally a Shiva temple (Kizhakkekara), where a subordinate Ganesha shrine grew to eclipse the main deity in popular devotion over time. Tradition holds a sculptor commissioned to carve a Vishnu idol was divinely guided to carve Ganesha instead, later consecrated by the legendary Kerala craftsman Perumthachan. The temple also holds a place in Kerala''s performing arts history as the site traditionally credited with the first-ever Kathakali performance, in the 17th century.' where name = 'Kottarakkara Ganapathy Temple';
update public.temples set native_name = 'हनुमान गढ़ी मन्दिर', best_season_notes = 'Oct–Feb; devotees traditionally visit here before proceeding to the Ram Mandir.', sthala_purana = 'A fort-like temple, blending Hindu and Indo-Islamic architectural styles, reached by 76 steps. Tradition holds this is the cave where Hanuman lived to guard Ramkot (Rama''s citadel) after Rama''s return from Lanka, and it remains customary for pilgrims to visit here before Ram Mandir darshan. Accounts of its founding vary — some crediting King Vikramaditya, others the poet-saint Tulsidas — and the present structure was rebuilt in the 18th century after Aurangzeb-era demolition.' where name = 'Hanuman Garhi Temple';
update public.temples set native_name = 'কঙ্কালীতলা মন্দির', best_season_notes = 'Oct–Feb; Navaratri and Kali Puja draw the largest crowds.', sthala_purana = 'One of the 51 Shakti Peethas, on the banks of the Kopai river, where tradition holds Sati''s waist (or, by some accounts, her bones — kankal) fell after Vishnu''s discus cut apart her body to end Shiva''s grief-stricken tandava. Unusually plain among the Shakti Peethas, the temple holds no metal, clay, or stone idol, worshipping instead at the sacred kund said to mark the spot itself.' where name = 'Kankalitala Temple';
update public.temples set native_name = 'नर्मदा उद्गम मन्दिर', best_season_notes = 'Oct–Feb; Narmada Jayanti draws the largest crowds.', sthala_purana = 'Marks the source of the Narmada river, alongside a cluster of 11th-century Kalachuri-era temples (Karna, Keshava Narayan, Machendranatha, Pateleshwar and others) around the Surya Kund, traditionally said to have been built up from a tank first created by Adi Shankaracharya in the 8th century. Tradition holds the rivers Narmada and Son, born here together, were betrothed to marry but Son abandoned Narmada at the altar — she flows west to the Arabian Sea in anger and disappointment, while Son flows east to join the Ganges.' where name = 'Narmada Udgam Temple, Amarkantak';

update public.temple_stays set price_range = 'Free to nominal donation, plus paid guest-house rooms', notes = 'Run by the temple trust itself, mostly within walking distance of the temple. Some rooms/beds are free or donation-based on a first-come, first-served basis (no advance booking); paid guest-house rooms are also available. The trust separately runs the free Annapoorna Choultry dining hall.' where name = 'Dharmasthala Temple Choultries and Guest Houses';
update public.temple_stays set price_range = '₹250–₹500/night', notes = 'Several guest-house blocks run by the temple itself, from budget triple rooms to AC suites. Book only through the temple’s own official channels — fake booking websites impersonating the temple have been reported.' where name = 'Kollur Mookambika Temple Guest Houses (Lalithamba, Sowparnika, Matha Chatra, Jagadmbika, and a dormitory)';
update public.temple_stays set price_range = 'Budget dormitory to family rooms', notes = 'Basic rooms operated by the temple trust rather than a private hotel, close to the temple’s thousand-pillared hall. Contact the devasthanam office directly to confirm current availability.' where name = 'Kanchipuram Devasthanam Rooms';
update public.temple_stays set price_range = 'Budget-priced', notes = null where name = 'Sri Kanchi Kamakoti Peetam Yatri Niwas';
update public.temple_stays set price_range = 'Mid-range, AC rooms available', notes = 'One of several guest houses run by the Srinath Trust itself, distinct from the many independent dharamshalas also clustered around the temple.' where name = 'New Cottage (run by the Srinath Trust)';
update public.temple_stays set price_range = '₹100–₹3,000/night; temple-managed AC rooms around ₹600–₹1,000', notes = 'A mix of temple-managed guest houses, cottages, and sadanams alongside government tourism accommodation, bookable through the temple’s own official portal.' where name = 'Bhadrachalam Temple Guest Houses and Sadanams';
update public.temple_stays set price_range = '₹75 (basic) to ₹1,500/night (suite cottages)', notes = 'Run directly by the temple devasthanam — several named cottages and a basic guest house/dharamshala. Allotted first-come, first-served; there is currently no online booking system.' where name = 'Basara Devasthanam Rooms and Cottages';
update public.temple_stays set price_range = '₹100–₹1,200/night', notes = 'One of the larger devasthanam accommodation operations in this list — around 400 rooms/dormitories/cottages on the hill itself, plus a further 60-room choultry and 30 halls downhill.' where name = 'Yadadri (Yadagirigutta) Devasthanam Rooms, Dormitories and Cottages';
update public.temple_stays set price_range = '₹300–₹700/night depending on room size and season', notes = '"Debutter" denotes temple-trust-owned property in this region — this guest house is run by the temple itself, distinct from the many independent lodges and homestays also on Nilachal Hill. Advance booking and photo ID are required.' where name = 'Kamakhya Debutter Guest House';
update public.temple_stays set price_range = 'Budget-priced', notes = 'Run directly by the temple trust; rooms are allotted on arrival at the counter rather than booked online, and photo ID is required.' where name = 'Shri Arasuri Ambaji Mata Devasthan Trust Rooms';
